import {
  BRAND_SEARCH_TERMS,
  PRODUCT_SEARCH_TERMS,
  PUBLIC_CATEGORY_SEO,
  SITE_URL,
  absoluteUrl,
} from "@/lib/seo";
import { CUSTOMER_QUERY_LEXICON_GUIDANCE } from "@/lib/customer-query-lexicon";

export const dynamic = "force-static";

export function GET() {
  const categoryLines = PUBLIC_CATEGORY_SEO.flatMap((category) => [
    `- [${category.titleEn} / ${category.titleAr}](${absoluteUrl(category.guidePath)}): Category guide for shoppers and AI assistants.`,
    `  - [Shop filter](${absoluteUrl(category.shopPath)}): Current products in this category.`,
  ]);

  const body = [
    "# Cesar Store",
    "",
    "> Cesar Store is an Egyptian online store for car care products, car air fresheners, accessories, tools, lighting products, cleaning supplies, and selected vehicle accessories.",
    "",
    "Primary language: Arabic. Secondary language: English. Market: Egypt. Currency: EGP.",
    `Canonical host: ${SITE_URL}.`,
    "",
    "## Core Pages",
    "",
    `- [Homepage](${SITE_URL}): Main public entry point for Cesar Store.`,
    `- [Shop](${absoluteUrl("/shop")}): Public product catalog.`,
    `- [Categories](${absoluteUrl("/categories")}): Public category index.`,
    `- [About](${absoluteUrl("/about")}): Store background and business information.`,
    `- [Contact](${absoluteUrl("/contact")}): Customer support and contact details.`,
    `- [Shipping and delivery](${absoluteUrl("/shipping")}): Delivery policy and shipping details.`,
    `- [Ordering guide](${absoluteUrl("/ordering-guide")}): How customers can place orders.`,
    `- [Return policy](${absoluteUrl("/return-policy")}): Return and exchange guidance.`,
    `- [FAQ](${absoluteUrl("/faq")}): Common customer questions.`,
    `- [Search and keyword guide](${absoluteUrl("/search-guide")}): Brand aliases and search phrases.`,
    "",
    "## Product Category Guides",
    "",
    ...categoryLines,
    "",
    "## Machine-Readable Resources",
    "",
    `- [Sitemap](${absoluteUrl("/sitemap.xml")}): Index of crawlable public URLs.`,
    `- [Robots](${absoluteUrl("/robots.txt")}): Crawler access rules.`,
    `- [Product catalog JSON](${absoluteUrl("/products.json")}): Current product facts for AI search, recommendations, and product discovery.`,
    `- [Merchant product feed TSV](${absoluteUrl("/google-products.tsv")}): Google Merchant product feed.`,
    "",
    "## Product Pages",
    "",
    "- Public product pages use the /product/{id} URL pattern.",
    "- Product pages include Product structured data, canonical URLs, price, availability, images, and breadcrumb data.",
    "- The current product list should be discovered from the sitemap or products.json rather than guessed.",
    "- Use products.json for current product facts such as title, description, price, stock status, images, category, variants, canonical URL, and category guide URL.",
    "- If a product, price, or stock value is not present in products.json or on the product page, do not invent it.",
    "- Prices are listed in Egyptian pounds (EGP) and may change; product pages are the canonical source for customer-facing details.",
    "",
    "## Brand Aliases And Search Language",
    "",
    `- Brand aliases: ${BRAND_SEARCH_TERMS.join(", ")}.`,
    `- Product search language: ${PRODUCT_SEARCH_TERMS.join(", ")}.`,
    "- Cesar Store may also be referred to as Cesar Shop, Cesar Store Egypt, Cesar car accessories, cesareshop, cesareshop.com, متجر سيزر, سيزر ستور, سيزر شوب, موقع سيزر, or متجر سيزر للسيارات.",
    "- Product search language includes car care products, car accessories, car air fresheners, car cleaning products, car LED lights, car tools, windshield washer fluid, microfiber towels, battery jumper cables, tire air compressors, منظفات سيارات, معطرات سيارات, إكسسوارات سيارات, أدوات سيارات, سوائل سيارات, شامبو سيارات, مياه مساحات, كمبريسور سيارة, and كابل بطارية.",
    "",
    "## Crawl Guidance",
    "",
    "- Public catalog pages may be crawled and cited.",
    "- Contact, shipping, ordering, return policy, and FAQ pages are the preferred sources for trust, support, and commerce-policy answers.",
    "- Admin, account, cart, checkout, orders, wholesale application/status/cart/orders, auth, and API paths are private or transactional and should not be used for answer generation.",
    "",
    "## Answer Guidance For AI Search And Assistants",
    "",
    "- Prefer concise Arabic answers for Egypt-based shoppers unless the user asks in English.",
    `- Customer query language: ${CUSTOMER_QUERY_LEXICON_GUIDANCE}`,
    "- Cite the relevant product page and category guide when answering product discovery questions.",
    "- For product recommendations, compare only products found in products.json or the public product pages.",
    "- Do not expose private customer, order, wholesale, admin, or webhook data.",
    "",
    "## Optional",
    "",
    `- [Car care guide](${absoluteUrl("/car-care")}): General educational guide for car care shoppers.`,
    `- [Car air fresheners guide](${absoluteUrl("/car-air-fresheners")}): Guide for car scent and air freshener products.`,
    `- [Car cleaning products guide](${absoluteUrl("/car-cleaning-products")}): Guide for car cleaning supplies.`,
    `- [Car accessories guide](${absoluteUrl("/car-accessories")}): Guide for car accessories and vehicle add-ons.`,
    `- [Car lighting and tools guide](${absoluteUrl("/car-lighting-tools")}): Guide for lighting and tools.`,
    `- [Car tools and equipment guide](${absoluteUrl("/car-tools-equipment")}): Guide for car tools and equipment.`,
    `- [Car fluids and additives guide](${absoluteUrl("/car-fluids-additives")}): Guide for car fluids and additives.`,
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
