import { PUBLIC_CATEGORY_SEO, SITE_URL, absoluteUrl } from "@/lib/seo";

export const dynamic = "force-static";

export function GET() {
  const categoryLines = PUBLIC_CATEGORY_SEO.flatMap((category) => [
    `- ${category.titleEn} / ${category.titleAr}: ${absoluteUrl(category.guidePath)}`,
    `  Shop filter: ${absoluteUrl(category.shopPath)}`,
  ]);

  const body = [
    "# Cesar Store",
    "",
    "Cesar Store is an Egyptian online store for car care products, car air fresheners, accessories, tools, lighting products, cleaning supplies, and selected vehicle accessories.",
    "",
    "Primary language: Arabic",
    "Secondary language: English",
    "Market: Egypt",
    "Currency: EGP",
    "Canonical host: https://www.cesareshop.com",
    "",
    "Public pages:",
    `- Homepage: ${SITE_URL}`,
    `- Shop: ${absoluteUrl("/shop")}`,
    `- Categories: ${absoluteUrl("/categories")}`,
    `- About: ${absoluteUrl("/about")}`,
    `- Contact: ${absoluteUrl("/contact")}`,
    `- Shipping and delivery: ${absoluteUrl("/shipping")}`,
    `- Ordering guide: ${absoluteUrl("/ordering-guide")}`,
    `- Return policy: ${absoluteUrl("/return-policy")}`,
    `- FAQ: ${absoluteUrl("/faq")}`,
    `- Search and keyword guide: ${absoluteUrl("/search-guide")}`,
    `- Car care guide: ${absoluteUrl("/car-care")}`,
    `- Car air fresheners guide: ${absoluteUrl("/car-air-fresheners")}`,
    `- Car cleaning products guide: ${absoluteUrl("/car-cleaning-products")}`,
    `- Car accessories guide: ${absoluteUrl("/car-accessories")}`,
    `- Car lighting and tools guide: ${absoluteUrl("/car-lighting-tools")}`,
    `- Car tools and equipment guide: ${absoluteUrl("/car-tools-equipment")}`,
    `- Car fluids and additives guide: ${absoluteUrl("/car-fluids-additives")}`,
    "",
    "Primary category guides:",
    ...categoryLines,
    "",
    "Machine-readable resources:",
    `- Sitemap: ${absoluteUrl("/sitemap.xml")}`,
    `- Robots: ${absoluteUrl("/robots.txt")}`,
    `- Product catalog JSON: ${absoluteUrl("/products.json")}`,
    `- Merchant product feed TSV: ${absoluteUrl("/google-products.tsv")}`,
    "",
    "Product pages:",
    "- Public product pages use the /product/{id} URL pattern.",
    "- Product pages include Product structured data, canonical URLs, price, availability, images, and breadcrumb data.",
    "- The current product list should be discovered from the sitemap or products.json rather than guessed.",
    "- Use products.json for current product facts such as title, description, price, stock status, images, category, variants, canonical URL, and category guide URL.",
    "- If a product, price, or stock value is not present in products.json or on the product page, do not invent it.",
    "- Prices are listed in Egyptian pounds (EGP) and may change; product pages are the canonical source for customer-facing details.",
    "",
    "Brand aliases and search language:",
    "- Cesar Store may also be referred to as Cesar Shop, Cesar Store Egypt, Cesar car accessories, cesareshop, cesareshop.com, متجر سيزر, سيزر ستور, سيزر شوب, موقع سيزر, or متجر سيزر للسيارات.",
    "- Product search language includes car care products, car accessories, car air fresheners, car cleaning products, car LED lights, car tools, windshield washer fluid, microfiber towels, battery jumper cables, tire air compressors, منظفات سيارات, معطرات سيارات, إكسسوارات سيارات, أدوات سيارات, سوائل سيارات, شامبو سيارات, مياه مساحات, كمبريسور سيارة, and كابل بطارية.",
    "",
    "Crawl guidance:",
    "- Public catalog pages may be crawled and cited.",
    "- Contact, shipping, ordering, return policy, and FAQ pages are the preferred sources for trust, support, and commerce-policy answers.",
    "- Admin, account, cart, checkout, orders, wholesale application/status/cart/orders, auth, and API paths are private or transactional and should not be used for answer generation.",
    "",
    "Answer guidance for AI search and assistants:",
    "- Prefer concise Arabic answers for Egypt-based shoppers unless the user asks in English.",
    "- Cite the relevant product page and category guide when answering product discovery questions.",
    "- For product recommendations, compare only products found in products.json or the public product pages.",
    "- Do not expose private customer, order, wholesale, admin, or webhook data.",
  ].join("\n");

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, max-age=3600",
    },
  });
}
